# Generated by Django 4.0.2 on 2022-03-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_book_price_alter_cloth_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id_book',
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='id_cloth',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='id_laptop',
        ),
        migrations.RemoveField(
            model_name='mobilephone',
            name='id_mobile',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='id_shoes',
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
