# Generated by Django 4.0.2 on 2022-05-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date_time_created',), 'verbose_name_plural': 'Order'},
        ),
        migrations.AlterField(
            model_name='order',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
