# Generated by Django 4.0.2 on 2022-05-18 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0006_clothesmanufacturer_clothesstyle_laptopproducer_and_more'),
        ('store', '0004_alter_comment_comment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_in_sale', models.DecimalField(decimal_places=0, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=0, max_digits=8)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptopitem_creator', to=settings.AUTH_USER_MODEL)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptopitem_laptop', to='warehouse.laptop')),
            ],
            options={
                'verbose_name_plural': 'LaptopItem',
            },
        ),
        migrations.CreateModel(
            name='ClothesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_in_sale', models.DecimalField(decimal_places=0, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=0, max_digits=8)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothesitem_laptop', to='warehouse.clothes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothesitem_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ClothesItem',
            },
        ),
    ]
