# Generated by Django 4.0.2 on 2022-05-18 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_clothesmanufacturer_clothesstyle_laptopproducer_and_more'),
        ('customer', '0001_initial'),
        ('store', '0005_laptopitem_clothesitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_book', to='warehouse.book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_book_customer', to='customer.customer')),
            ],
            options={
                'verbose_name_plural': 'CommentBook',
            },
        ),
        migrations.CreateModel(
            name='CommentClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_clothes', to='warehouse.laptop')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_clothes_customer', to='customer.customer')),
            ],
            options={
                'verbose_name_plural': 'CommentClothes',
            },
        ),
        migrations.CreateModel(
            name='CommentLaptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_laptop_customer', to='customer.customer')),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_laptop', to='warehouse.laptop')),
            ],
            options={
                'verbose_name_plural': 'CommentLaptop',
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
