# Generated by Django 4.0.2 on 2022-05-18 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_clothesmanufacturer_clothesstyle_laptopproducer_and_more'),
        ('store', '0006_commentbook_commentclothes_commentlaptop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentclothes',
            name='clothes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_clothes', to='warehouse.clothes'),
        ),
    ]
