# Generated by Django 4.0.2 on 2022-05-18 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_commentclothes_clothes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_book', to='store.bookitem'),
        ),
        migrations.AlterField(
            model_name='commentclothes',
            name='clothes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_clothes', to='store.clothesitem'),
        ),
        migrations.AlterField(
            model_name='commentlaptop',
            name='laptop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_laptop', to='store.laptopitem'),
        ),
    ]
