# Generated by Django 4.0.2 on 2022-05-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_commentbook_book_alter_commentclothes_clothes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentbook',
            old_name='book',
            new_name='book_item',
        ),
        migrations.RenameField(
            model_name='commentclothes',
            old_name='clothes',
            new_name='clothes_item',
        ),
        migrations.RenameField(
            model_name='commentlaptop',
            old_name='laptop',
            new_name='laptop_item',
        ),
    ]
