# Generated by Django 4.0.2 on 2022-05-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_commentbook_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentclothes',
            options={'ordering': ('-comment_time',), 'verbose_name_plural': 'CommentClothes'},
        ),
        migrations.AlterModelOptions(
            name='commentlaptop',
            options={'ordering': ('-comment_time',), 'verbose_name_plural': 'CommentLaptop'},
        ),
    ]
