# Generated by Django 4.0.2 on 2022-05-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('-fullname',), 'verbose_name_plural': 'Author'},
        ),
    ]
