# Generated by Django 4.0.2 on 2022-05-18 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0005_alter_book_category_alter_book_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Clothes manufacturer',
            },
        ),
        migrations.CreateModel(
            name='ClothesStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Clothes style',
            },
        ),
        migrations.CreateModel(
            name='LaptopProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Laptop producer',
            },
        ),
        migrations.CreateModel(
            name='LaptopType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Laptop type',
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('-fullname',), 'verbose_name_plural': 'Book author'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',), 'verbose_name_plural': 'Book category'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ('-name',), 'verbose_name_plural': 'Book publisher'},
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('size_screen', models.DecimalField(decimal_places=0, max_digits=8)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=8)),
                ('price', models.DecimalField(decimal_places=0, max_digits=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptop_creator', to=settings.AUTH_USER_MODEL)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptop_producer', to='warehouse.laptopproducer')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptop_type', to='warehouse.laptoptype')),
            ],
            options={
                'verbose_name_plural': 'Laptops',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=8)),
                ('price', models.DecimalField(decimal_places=0, max_digits=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_creator', to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_manufacturer', to='warehouse.clothesmanufacturer')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_style', to='warehouse.clothesstyle')),
            ],
            options={
                'verbose_name_plural': 'Clothes',
                'ordering': ('-created',),
            },
        ),
    ]
