# Generated by Django 4.0.2 on 2022-05-18 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_laptopitem_clothesitem'),
        ('cart', '0003_alter_cartbookitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartbookitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_book', to='cart.cart'),
        ),
        migrations.CreateModel(
            name='CartLaptopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=8)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_laptop', to='cart.cart')),
                ('laptop_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitem_laptopitem', to='store.laptopitem')),
            ],
            options={
                'verbose_name_plural': 'CartLaptopItem',
            },
        ),
        migrations.CreateModel(
            name='CartClothesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=8)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_clothes', to='cart.cart')),
                ('clothes_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitem_clothesitem', to='store.clothesitem')),
            ],
            options={
                'verbose_name_plural': 'CartClothesItem',
            },
        ),
    ]
